version: "3.8"

services:
    nginx:
        depends_on:
            - wordpress
        container_name: nginx
        build: requirements/nginx
        image: nginx
        ports:
            - "443:443"
        volumes:
            - /home/bledda/data/wp-data:/var/www/wordpress/
        networks:
            - bledda-network
        restart: always

    wordpress:
        depends_on:
            - mariadb
        container_name: wordpress
        build: requirements/wordpress
        image: wordpress
        expose:
            - "9000"
        volumes:
            - /home/bledda/data/wp-data:/var/www/wordpress
        networks:
            - bledda-network
        restart: always
    
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        image: mariadb
        environments:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        expose:
            - "3306"
        networks:
            - bledda-network
        restart: always

networks:
    bledda-network:
        name: bledda-network
        driver: bridge
