version: "3.8"

services:
    nginx:
        depends_on:
            - wordpress
        container_name: nginx
        build: requirements/nginx
        image: nginx
        ports:
            - "443:443"
        volumes:
            - /home/bledda/data/wp-data:/var/www/wordpress/
        networks:
            - bledda-network
        restart: always

    wordpress:
        container_name: wordpress
        build: requirements/wordpress
        image: wordpress
        expose:
            - "9000"
        volumes:
            - /home/bledda/data/wp-data:/var/www/wordpress
        networks:
            - bledda-network
        restart: always

networks:
    bledda-network:
        name: bledda-network
        driver: bridge
