version: "3.8"

services:
    nginx:
        depends_on:
            - wordpress
        container_name: nginx
        build:
            context:  requirements/nginx
            args:
                DOMAIN_NAME: ${DOMAIN_NAME}
        image: nginx
        env_file:
            - .env
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/wordpress/
        networks:
            - bledda-network
        restart: always

    wordpress:
        depends_on:
            - mariadb
        container_name: wordpress
        build: requirements/wordpress
        image: wordpress
        env_file:
            - .env
        expose:
            - "9000"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - bledda-network
        restart: always

    mariadb:
        container_name: mariadb
        build:
            context:  requirements/mariadb
            args:
                DB_WP: ${DB_WP}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        image: mariadb
        env_file:
            - .env
        expose:
            - "3306"
        volumes:
            - mariadb:/var/lib/mysql/${DB_WP}
        networks:
            - bledda-network
        restart: always

networks:
    bledda-network:
        name: bledda-network
        driver: bridge

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none  
            o: bind
            device: /home/bledda/data/wp-data

    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none  
            o: bind
            device: /home/bledda/data/db-data
