version: "3.8"
services:
    nginx:
        depends_on:
            - wordpress
        container_name: nginx
        build: requirements/nginx
        image: nginx
        ports:
            - "443:443"
        volumes:
            - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./requirements/wordpress/website/:/var/www/wordpress/
        networks:
            - bledda-network
        restart: always
        privileged: true

    wordpress:
        container_name: wordpress
        build: requirements/wordpress
        image: wordpress
        volumes:
            - ./requirements/wordpress/conf/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
            - ./requirements/wordpress/website/:/var/www/wordpress
        networks:
            - bledda-network
        restart: always
        privileged: true

networks:
    bledda-network:
        name: bledda-network
        driver: bridge