FROM	debian:buster

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN 	apt-get install -y \
			mariadb-server

COPY	tools/setup.sh /

RUN		./setup.sh && rm -f setup.sh

COPY	conf/50-server.cnf /etc/mysql/mariadb.conf.d/

EXPOSE 	3306

CMD		service mysql start && tail -f /dev/null
