FROM 	debian:buster

ARG		DOMAIN_NAME

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN 	apt-get install -y \
			lsb-release \
			apt-transport-https \
			ca-certificates \
			wget \
			curl \
			nginx

RUN		wget -O \
			/etc/apt/trusted.gpg.d/php.gpg \
			https://packages.sury.org/php/apt.gpg

RUN		echo \
			"deb https://packages.sury.org/php/ \
			$(lsb_release -sc) main" \
			| tee /etc/apt/sources.list.d/php.list

RUN		apt-get update -y

RUN		apt-get install -y \
			php8.0 \
			php8.0-fpm \
			php8.0-mysqli


COPY	conf/default.conf /etc/nginx/conf.d/default.conf

ADD		\
		https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php \
		/var/www/

WORKDIR /var/www/
RUN		chmod 644 adminer-4.8.1.php

RUN		rm -rf html

CMD 	service nginx start && service php8.0-fpm start && tail -f
