FROM	debian:buster

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN		apt-get install -y \
			lsb-release \
			apt-transport-https \
			ca-certificates \
			wget \
			tar

RUN		wget -O \
			/etc/apt/trusted.gpg.d/php.gpg \
			https://packages.sury.org/php/apt.gpg

RUN		echo \
			"deb https://packages.sury.org/php/ \
			$(lsb_release -sc) main" \
			| tee /etc/apt/sources.list.d/php.list

RUN		apt-get update -y

RUN		apt-get install -y \
			php8.0 \
			php8.0-fpm \
			php8.0-mysqli

RUN		wget \
			https://fr.wordpress.org/wordpress-5.8.2-fr_FR.tar.gz -P \/

COPY	conf/www.conf /etc/php/8.0/fpm/pool.d/www.conf

COPY	conf/wp-config.php /

COPY	tools/init.sh /init.sh

EXPOSE	9000

STOPSIGNAL SIGQUIT

CMD		./init.sh; php-fpm8.0 -F
