FROM	debian:buster

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN		apt-get install -y \
			lsb-release \
			apt-transport-https \
			ca-certificates \
			wget

RUN		wget -O \
			/etc/apt/trusted.gpg.d/php.gpg \
			https://packages.sury.org/php/apt.gpg

RUN		echo \
			"deb https://packages.sury.org/php/ \
			$(lsb_release -sc) main" \
			| tee /etc/apt/sources.list.d/php.list

RUN		apt-get update -y

RUN		apt-get install -y \
			php8.0 \
			php8.0-fpm \
			php8.0-mysqli

COPY	conf/www.conf /etc/php/8.0/fpm/pool.d/www.conf

RUN		mkdir -p /run/php

ADD		https://fr.wordpress.org/wordpress-5.8.2-fr_FR.tar.gz \
			/var/www/

WORKDIR /var/www/
RUN		tar -xzvf wordpress-5.8.2-fr_FR.tar.gz \
			&& rm -f wordpress-5.8.2-fr_FR.tar.gz

COPY	conf/wp-config.php /var/www/wordpress/wp-config.php

WORKDIR /var/www/wordpress/
RUN		chmod 644 wp-config.php

EXPOSE	9000

ENTRYPOINT	["php-fpm8.0"]
CMD			["-F"]
