FROM	debian:buster

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN 	apt-get -y install wget lsb-release apt-transport-https ca-certificates \
			wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
			echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN		apt-get update -y \
			&& apt-get upgrade -y \
			&& apt-get -y install php7.4 nginx php7.4-fpm mariadb-server unzip php7.4-xml php7.4-mysqli php7.4-mbstring \
			&& apt-get -y update && apt-get -y upgrade

EXPOSE	9000

CMD		service php7.4-fpm start && tail -f /dev/null