FROM	debian:buster

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN		apt-get install -y \
			wget \
			udev

RUN		wget \
		https://downloads.plex.tv/plex-media-server-new/1.16.5.1488-deeb86e7f/debian/plexmediaserver_1.16.5.1488-deeb86e7f_amd64.deb

RUN		dpkg -i plexmediaserver_1.16.5.1488-deeb86e7f_amd64.deb

# CMD		/usr/lib/plexmediaserver/Plex\ Media\ Server

EXPOSE 32400

CMD [ "tail", "-f" ]