FROM 	debian:buster

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN 	apt-get install -y \
			nginx \
			openssl

ARG		DOMAIN_NAME

RUN		openssl \
			req -x509 -nodes -days 365 -newkey rsa:2048 \
			-keyout /etc/nginx/conf.d/local.key \
			-out /etc/nginx/conf.d/local.crt \
			-subj \
			"/C=FR/ST=PACA/L=Nice/O=42 Nice/CN=${DOMAIN_NAME}"

COPY	conf/default.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT	["nginx"]
CMD 		["-g", "daemon off;"]
