FROM 	debian:buster

ARG		DOMAIN_NAME

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN 	apt-get install -y \
			nginx \
			openssl

RUN		mkdir -p /etc/nginx/ssl/public/
RUN		mkdir -p /etc/nginx/ssl/private/

RUN		openssl \
			req -x509 -nodes -days 365 -newkey rsa:2048 \
			-keyout /etc/nginx/ssl/private/wordpress.key \
			-out /etc/nginx/ssl/public/wordpress.crt \
			-subj \
			"/C=FR/ST=PACA/L=Nice/O=42 Nice/CN=${DOMAIN_NAME}"

COPY	conf/default.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT	["nginx"]
CMD 		["-g", "daemon off;"]
