FROM 	debian:buster

ARG		DOMAIN_NAME

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN 	apt-get install -y \
			nginx \
			openssl

RUN		mkdir -p /etc/nginx/ssl/public/
RUN		mkdir -p /etc/nginx/ssl/private/

RUN		openssl \
			req -x509 -nodes -days 365 -newkey rsa:2048 \
			-keyout /etc/nginx/ssl/private/wordpress.key \
			-out /etc/nginx/ssl/public/wordpress.crt \
			-subj \
			"/C=FR/ST=PACA/L=Nice/O=42 Nice/CN=${DOMAIN_NAME}"

RUN		openssl \
			req -x509 -nodes -days 365 -newkey rsa:2048 \
			-keyout /etc/nginx/ssl/private/website.key \
			-out /etc/nginx/ssl/public/website.crt \
			-subj \
			"/C=FR/ST=PACA/L=Nice/O=42 Nice/CN=website.bledda.42.fr"

RUN		openssl \
			req -x509 -nodes -days 365 -newkey rsa:2048 \
			-keyout /etc/nginx/ssl/private/plex.key \
			-out /etc/nginx/ssl/public/plex.crt \
			-subj \
			"/C=FR/ST=PACA/L=Nice/O=42 Nice/CN=plex.bledda.42.fr"

RUN		openssl \
			req -x509 -nodes -days 365 -newkey rsa:2048 \
			-keyout /etc/nginx/ssl/private/adminer.key \
			-out /etc/nginx/ssl/public/adminer.crt \
			-subj \
			"/C=FR/ST=PACA/L=Nice/O=42 Nice/CN=adminer.bledda.42.fr"

RUN		rm -f /etc/nginx/conf.d/default.conf
RUN		rm -f /etc/nginx/sites-enabled/default

COPY	conf/wordpress.conf /etc/nginx/conf.d/wordpress.conf
COPY	conf/website.conf /etc/nginx/sites-enabled/website
COPY	conf/plex.conf /etc/nginx/sites-enabled/plex
COPY	conf/adminer.conf /etc/nginx/sites-enabled/adminer

COPY	conf/nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT	["nginx"]
CMD 		["-g", "daemon off;"]
