FROM	debian:buster

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN		apt-get install -y \
			openssh-server \
			git

RUN		useradd git -m
RUN		mkdir /home/git/.ssh
COPY	conf/authorized_keys /home/git/.ssh/authorized_keys
RUN		chown -R git:git /home/git
RUN		chmod -R 700 /home/git

RUN 	mkdir -p /run/sshd/

CMD		["/usr/sbin/sshd", "-D", "-e"]
